@echo off
rem Compatibility shim for the scripts/dev/*-windows.cmd wrappers.
rem The real Windows environment is generated by scripts/setup-windows.ps1 and
rem loaded from .cargo/env-windows.bat. Do not set absolute CC/CXX paths here.

if "%AGAVE_WINDOWS_CARGO_ENV_READY%"=="1" goto :eof
set "AGAVE_WINDOWS_CARGO_ENV_READY=1"

set "AGAVE_ROOT=%~dp0..\..\.."
for %%I in ("%AGAVE_ROOT%") do set "AGAVE_ROOT=%%~fI"

if not exist "%AGAVE_ROOT%\.cargo\env-windows.bat" (
  powershell -NoProfile -ExecutionPolicy Bypass -File "%AGAVE_ROOT%\scripts\setup-windows.ps1"
  if errorlevel 1 exit /b %ERRORLEVEL%
)

call "%AGAVE_ROOT%\.cargo\env-windows.bat"
goto :eof
